server:
  port: 9001

spring:
  application:
    name: cloudalibaba-nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.58:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

