server:
  port: 9004

spring:
  application:
    name: cloudalibaba-nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.58:8848
    sentinel:
      transport:
        dashboard: 192.168.10.58:8888


management:
  endpoints:
    web:
      exposure:
        include: "*"
