server:
  port: 83

spring:
  application:
    name: cloudalibaba-nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.58:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
