server:
  port: 84
spring:
  application:
    name: cloudalibaba-nacos-consumer-order

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.58:8848
    sentinel:
      transport:
        dashboard: 192.168.10.58:8888

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
